services:
  application:
    build:
      context: .
      dockerfile: docker/DockerFile
    container_name: application
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel_app
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_app
    # db:
    #   image: mysql:8.0
    #   platform: linux/x86_64
    #   restart: unless-stopped
    #   environment:
    #       MYSQL_DATABASE: ${DB_DATABASE:-laravel}
    #       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    #       MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
    #       MYSQL_USER: ${DB_USERNAME:-username}
    #   volumes:
    #       - ./.docker/mysql/dbdata:/var/lib/mysql
    #   ports:
    #       - "3300:3306"
    #   networks:
    #       - laravel_app
  # redis:
  #   image: redis:latest
  #   networks:
  #       - laravel_app
networks:
  laravel_app:
    driver: bridge